"""Portfolio mazmuni. Matnni o'zgartirish uchun shu faylni tahrirlang, keyin: python build.py"""

SITE = {
    "name": "Dinmuhammad",
    "role": "Full-stack dasturchi",
    "url": "https://dinmuhammad05.github.io",
    "telegram": "@dinMuhammad05",
    "telegram_url": "https://t.me/dinMuhammad05",
    "github_url": "https://github.com/dinmuhammad05",
}

SERVICES = [
    {
        "icon": "⚙️",
        "title": "Biznesni avtomatlashtirish",
        "text": "Qo‘lda, daftar va jadvalda qilinadigan ishlarni bitta tizimga o‘tkazish.",
        "items": ["CRM va ichki ERP", "Kassa, ombor va hisobotlar", "Qabul yozuvi va SMS eslatmalar", "Rollar va xodimlar nazorati"],
        "examples": ["apteka-crm", "klinika-erp", "techjobs"],
        "accent": True,
    },
    {
        "icon": "✈️",
        "title": "Telegram botlar",
        "text": "Mijoz va jamoa allaqachon o‘tirgan joyda ishlaydigan avtomatika.",
        "items": ["Kanalga avtomatik postlar", "Ommaviy va shaxsiy xabarnomalar", "Bot orqali ariza va buyurtma", "Signal va monitoring botlari"],
        "examples": ["techjobs", "topkan", "autotrad"],
    },
    {
        "icon": "🧩",
        "title": "SaaS va veb-ilovalar",
        "text": "Bir nechta mijoz yoki filialga xizmat qiladigan to‘liq mahsulot.",
        "items": ["Ko‘p tashkilotli arxitektura", "Obuna va tariflar", "Admin va super-admin panellar", "Ko‘p tilli interfeys"],
        "examples": ["topkan", "apteka-crm", "falaq"],
    },
    {
        "icon": "🔌",
        "title": "Integratsiyalar",
        "text": "Tizimingizni to‘lov, SMS va boshqa xizmatlar bilan ulash.",
        "items": ["Payme, Click, Uzum", "SMS (Eskiz) va OTP", "Google, Apple, LinkedIn orqali kirish", "AI (LLM) va fayl omborlari"],
        "examples": ["almazpro", "falaq", "topkan"],
    },
]

PROJECTS = [
    {
        "slug": "topkan",
        "tag": "HR SaaS",
        "title": "Topkan — AI bilan nomzod tanlash",
        "name": "Topkan",
        "site": ("https://topkan.uz", "topkan.uz"),
        "role": "Full-stack · backend, veb-ilova, AI va Telegram",
        "summary": "HR vakansiya yaratadi, tizim “smart-link” beradi, HR uni Telegram kanallarida ulashadi. Nomzodlar havola yoki bot orqali topshiradi, har bir rezyume esa vakansiya talablariga moslik bo‘yicha <b>0–100 ball</b> bilan avtomatik baholanadi.",
        "points": [
            "Rezyumeni (PDF, DOCX) o‘qib, LLM orqali tuzilmali baholash — navbatda, asinxron",
            "Nomzodlar voronkasi (kanban), intervyular, avtomatlashtirish va xabarnomalar",
            "Ko‘p tashkilotli SaaS: rollar, tariflar va to‘lov",
            "Google va LinkedIn orqali parolsiz kirish, S3 da presigned yuklash",
        ],
        "stack": ["NestJS", "Prisma", "PostgreSQL", "Redis · BullMQ", "Next.js", "Claude API", "Telegram Bot"],
        "featured": True,
        "problem": "Telegram kanaliga vakansiya joylagan HR yuzlab rezyume oladi va ularni qo‘lda o‘qib chiqadi. Qaysi kanal yaxshi nomzod berayotganini bilmaydi, eng mos nomzodlar esa ro‘yxat oxirida qolib ketadi. Topkan bu ishni avtomatlashtiradi: HR faqat saralangan eng yaxshi nomzodlar bilan ishlaydi.",
        "my_role": "Loyihani to‘liq qurdim: ma’lumotlar modeli va NestJS backend, Next.js veb-ilova (HR paneli va nomzod kabineti), AI baholash quvuri, Telegram bot, serverga joylash va avtomatik deploy.",
        "features": [
            ("HR uchun", [
                "Vakansiya yaratish va e’lon qilish — tokenli “smart-link” avtomatik yaratiladi",
                "Har bir kanal uchun alohida link: klik, arizalar, o‘rtacha ball va konversiya bo‘yicha kanallarni solishtirish",
                "Saralangan nomzodlar paneli: qidiruv, holat va minimal ball bo‘yicha filtr, bir nechtasini birdan o‘zgartirish, ichki izohlar",
                "Nomzodlar voronkasi (kanban), intervyular va Google Calendar / Meet integratsiyasi",
                "Jamoa: rekruter taklif qilish (link 7 kunda eskiradi), chiqarish — o‘chirish emas, deaktivatsiya",
            ]),
            ("Nomzod uchun", [
                "Havola orqali yoki Telegram bot orqali ariza topshirish",
                "Google / LinkedIn bilan kirish, shaxsiy kabinetda arizalar holati",
            ]),
            ("AI baholash", [
                "Rezyume matni PDF va DOCX dan ajratiladi, vakansiya talablari bilan birga LLM ga yuboriladi",
                "Natija — tuzilmali JSON (tool-use): 0–100 ball va asoslash",
                "Skrining savollari: “knockout” javob kelsa ariza avtomatik rad etiladi va LLM ga umuman yuborilmaydi — token tejaladi",
                "Baholash tugagach, tashkilotning Telegram chatiga xulosa keladi",
            ]),
        ],
        "arch": [
            ("Mijozlar", ["Next.js veb-ilova", "Telegram bot", "Smart-link sahifasi"]),
            ("API", ["NestJS modullari", "OAuth + JWT", "Rollar va tashkilotlar"]),
            ("Fon ishlari", ["BullMQ navbati", "Rezyume parser", "LLM scoring worker"]),
            ("Ma’lumot", ["PostgreSQL (Prisma)", "Redis", "S3 / MinIO"]),
        ],
        "decisions": [
            ("Baholash — so‘rov yo‘lida emas, navbatda", "LLM javobi soniyalar oladi va ba’zan xato qaytaradi. Shuning uchun ariza darhol qabul qilinadi, baholash esa BullMQ navbatida alohida worker jarayonida bajariladi — qayta urinish bilan. Nomzod kutib qolmaydi, API tez qoladi."),
            ("LLM dan erkin matn emas, tuzilma", "Model javobi tool-use orqali qat’iy JSON sxemasiga majburlanadi. Shunda ball va asoslashni to‘g‘ridan-to‘g‘ri bazaga yozish, filtrlash va saralash mumkin — matnni “parse” qilish kerak emas."),
            ("Arzon filtr — qimmat modeldan oldin", "Skrining savollaridagi knockout javoblar LLM chaqiruvidan oldin tekshiriladi. Mos kelmaydigan arizalar uchun token sarflanmaydi."),
            ("Fayllar serverdan o‘tmaydi", "Rezyume va fayllar presigned URL orqali to‘g‘ridan-to‘g‘ri S3 ga yuklanadi — API xotirasi va tarmog‘i band bo‘lmaydi."),
        ],
    },
    {
        "slug": "falaq",
        "tag": "Platforma",
        "title": "Falaq — audio va elektron kitoblar",
        "name": "Falaq",
        "site": None,
        "site_label": "Falaq nashriyoti",
        "role": "Backend, veb-sayt va admin panel · mobil ilova boshqa jamoa a’zosida",
        "summary": "Kitobni bir marta sotib olib, uni onlayn tinglash va o‘qish, hamda internetsiz ishlatish mumkin bo‘lgan platforma. Asosiy muhandislik vazifasi — <b>kontentni himoyalash</b>: fayllar shifrlangan, kalit qurilmaga bog‘langan.",
        "points": [
            "Kontent quvuri: yuklash → AES-256 envelope shifrlash (navbatda) → Cloudflare R2",
            "Oflayn kirish litsenziyasi: 30 kunlik muddat, qurilmalar nazorati",
            "Xarid, obuna va litsenziya; telefon OTP va Google / Apple orqali kirish",
            "4 tilli API (uz lotin, uz kirill, ru, en), Swagger hujjatlari",
        ],
        "stack": ["NestJS 11", "TypeORM", "PostgreSQL", "Redis · BullMQ", "Cloudflare R2", "Next.js", "React"],
        "featured": True,
        "problem": "Nashriyot audio va elektron kitoblarni sotmoqchi, lekin bitta shart bilan: sotib olingan kitob internetsiz ham ishlashi kerak, va shu bilan birga fayl ko‘chirib tarqatilmasligi kerak. Bu ikki talab bir-biriga zid: fayl qurilmada bo‘lishi kerak, lekin undan foydalanib bo‘lmasligi kerak.",
        "my_role": "Backend (NestJS, modulli monolit), mijozlar uchun veb-sayt va admin panelni qildim. Mobil ilova (Flutter) boshqa jamoa a’zosi tomonidan qilingan — men unga API va integratsiya hujjatlarini tayyorladim.",
        "features": [
            ("Kontent va himoya", [
                "Har bir fayl uchun alohida tasodifiy kalit (DEK), fayl AES-256-CTR bilan shifrlanadi — audio’ni surish va HTTP Range uchun",
                "Kalitlar master kalit (KEK) bilan AES-256-GCM da o‘raladi; bazada faqat o‘ralgan kalit turadi",
                "Omborda (R2) hech qachon ochiq fayl turmaydi — hatto bepul namuna ham shifrlangan",
                "Katta fayllar brauzerdan to‘g‘ridan-to‘g‘ri R2 ga yuklanadi (presigned PUT), shifrlash navbatda",
            ]),
            ("Kirish va litsenziya", [
                "Bir martalik xarid: bitta xarid kitobning audio va elektron variantini ochadi",
                "Oflayn litsenziya 30 kun amal qiladi, keyin internetga ulanib yangilanadi",
                "Qurilmalar ro‘yxati va nazorati",
                "Telefon OTP (Eskiz SMS) + Google / Apple OAuth, JWT rotatsiyasi bilan",
            ]),
            ("Platforma", [
                "Katalog, kutubxona, sharh va reyting, bildirishnomalar, obunalar",
                "4 tilli API: o‘zbek (lotin va kirill), rus, ingliz",
                "Admin panel: kitoblar, nashrlar, fayllar yuklash, foydalanuvchilar",
            ]),
        ],
        "arch": [
            ("Mijozlar", ["Flutter ilova", "Next.js sayt", "React admin panel"]),
            ("API", ["NestJS modulli monolit", "Auth + OTP", "Kirish va litsenziya"]),
            ("Fon ishlari", ["BullMQ: shifrlash", "Preview tayyorlash"]),
            ("Ma’lumot", ["PostgreSQL (TypeORM)", "Redis (OTP, navbat)", "Cloudflare R2"]),
        ],
        "decisions": [
            ("Envelope encryption", "Har fayl o‘z kaliti bilan shifrlanadi, kalitlar esa master kalit bilan o‘raladi. Master kalitni almashtirish kerak bo‘lsa, 500 MB li fayllarni qayta shifrlash shart emas — faqat kichik kalitlar qayta o‘raladi. Har faylning alohida kaliti tufayli bepul namuna kaliti pullik kontentni ochmaydi."),
            ("CTR rejimi — audio uchun", "Kontent AES-CTR bilan shifrlangan: bu faylning istalgan joyidan o‘qish imkonini beradi. Foydalanuvchi audio’ni o‘rtasiga sursa, butun faylni ochish shart emas."),
            ("Fayllar API dan o‘tmaydi", "Yuklash ham, yuklab olish ham presigned URL orqali to‘g‘ridan-to‘g‘ri R2 bilan. Server faqat kalitlar va ruxsatlar bilan ishlaydi — katta fayllar uning xotirasini band qilmaydi. R2 tanlovi ham shu bilan bog‘liq: chiqish trafigi bepul."),
            ("Muddatli oflayn litsenziya", "Oflayn kalit 30 kunlik. Obuna yoki huquq tugasa, qurilma keyingi ulanishda kalitni yangilay olmaydi — fayl o‘chirilmasa ham foydasiz bo‘ladi."),
        ],
    },
    {
        "slug": "techjobs",
        "tag": "ERP · Telegram bot",
        "title": "TechJobs — ichki ERP va Telegram bot",
        "name": "TechJobs",
        "site": ("https://techjobs.uz", "techjobs.uz"),
        "role": "Full-stack · ichki boshqaruv tizimi (ERP) va Telegram bot",
        "summary": "IT mutaxassislar va ish beruvchilarni bog‘laydigan platformaning <b>ichki boshqaruv tizimi</b>: ish beruvchilarni tekshirish, vakansiyalar moderatsiyasi, obunalar va to‘lovlar, statistika — va bularning hammasi bilan bog‘langan Telegram bot.",
        "points": [
            "Ish beruvchi akkauntlarini tasdiqlash, vakansiyalarni tekshirish va moderatsiya",
            "Obunalar, promo-kodlar, Click va Payme to‘lovlari nazorati",
            "Telegram bot: yangi vakansiyalarni kanalga avtomatik joylash, ommaviy xabar yuborish",
            "Statistika paneli, kategoriya / kasb / ko‘nikmalar katalogi",
        ],
        "stack": ["NestJS", "TypeORM", "PostgreSQL", "Redis", "Next.js", "TanStack Query", "Telegram Bot API"],
        "featured": False,
        "problem": "Ochiq platformada har kuni yangi kompaniyalar, vakansiyalar va nomzodlar paydo bo‘ladi. Ularni tekshirish, soxta e’lonlarni to‘xtatish, obunalar va to‘lovlarni kuzatish va vakansiyalarni Telegram kanalga chiqarish uchun jamoaga ichki vosita kerak edi — qo‘lda, jadval va chatlar orqali bu ishlamaydi.",
        "my_role": "Platformaning ichki ERP qismini — admin API va boshqaruv panelini — hamda Telegram bot integratsiyasini qildim.",
        "features": [
            ("Moderatsiya", [
                "Yangi ish beruvchilarni tasdiqlash yoki rad etish (kutilayotganlar ro‘yxati)",
                "Vakansiyalarni tekshirish, tahrirlash va o‘chirish",
                "Nomzodlar holatini boshqarish",
            ]),
            ("Tijorat", [
                "Ish beruvchilar obunalari va ularning tarixi",
                "Promo-kodlar: yaratish, yoqish / o‘chirish",
                "Click va Payme orqali to‘lovlar",
            ]),
            ("Telegram", [
                "Yangi vakansiya tasdiqlanganda kanalga avtomatik post: kompaniya, lavozim, talablar, maosh va ariza havolasi",
                "Nomzodlarga ommaviy xabar — filtr bo‘yicha, bo‘laklab (batch) yuborish bilan",
                "Arizalar, holat o‘zgarishi va ishga olinish haqida shaxsiy xabarlar",
                "Bot /start orqali foydalanuvchini platformadagi akkauntiga bog‘lash; webhook rejimi",
            ]),
            ("Ma’lumotlar va statistika", [
                "Kategoriya, kasb va ko‘nikmalar katalogi — butun platforma uchun yagona manba",
                "Statistika va tahlil paneli",
                "Cron: eskirgan vakansiyalar va vaqtinchalik fayllarni tozalash",
            ]),
        ],
        "arch": [
            ("Foydalanuvchilar", ["Admin panel (Next.js)", "Telegram kanal va bot"]),
            ("API", ["Admin modullari", "Rollar: admin / super-admin", "To‘lovlar"]),
            ("Integratsiyalar", ["Telegram Bot API (webhook)", "Click / Payme"]),
            ("Ma’lumot", ["PostgreSQL", "Redis kesh", "Cron vazifalar"]),
        ],
        "decisions": [
            ("Ommaviy xabar — bo‘laklab", "Minglab nomzodga bir vaqtda xabar yuborish Telegram cheklovlariga uriladi. Xabarlar bo‘laklarga ajratilib, navbat bilan yuboriladi va har biri uchun natija hisoblanadi."),
            ("Vakansiya posti — shablondan", "Kanalga chiqadigan post vakansiya ma’lumotidan avtomatik yig‘iladi: bir xil ko‘rinish, xatosiz havola, qo‘lda nusxalash yo‘q."),
            ("Katalog — yagona manba", "Kategoriya, kasb va ko‘nikmalar bitta joyda boshqariladi; vakansiya, nomzod profili va qidiruv shu katalogga tayanadi."),
        ],
        "numbers": [("~2.5 ms", "platformaning o‘rtacha javobi, 1 000 parallel foydalanuvchi (k6 testi)"), ("2 500+", "so‘rov/s — platformaning maksimal quvvati")],
    },
    {
        "slug": "apteka-crm",
        "tag": "SaaS · POS",
        "title": "Apteka CRM — dorixonalar uchun kassa va ombor",
        "name": "Apteka CRM",
        "site": None,
        "site_label": "Apteka CRM",
        "role": "Full-stack · backend va frontend",
        "summary": "Ko‘p dorixonali SaaS: kassa, ombor, hisobotlar va super-admin konsoli (obuna tugasa dorixona avtomatik bloklanadi).",
        "points": [
            "Shtrix-kod skaneri bilan kassa, qadoq va dona bo‘yicha sotish, chegirmalar",
            "Partiyalar va yaroqlilik muddati, kam qolgan tovarlar ogohlantirishi",
            "Yetkazib beruvchi nakladnoylarini Excel’dan import",
            "Smenalar, xarajatlar, mijozlar va Telegram xabarnomalar; uz / ru / tg",
        ],
        "stack": ["NestJS", "Prisma", "PostgreSQL", "React 19", "Vite", "TanStack Query", "Tailwind"],
        "featured": False,
        "problem": "Kichik dorixonalar ko‘pincha daftar yoki eski dasturda ishlaydi: qoldiq noaniq, muddati o‘tgan dori vaqtida ko‘rinmaydi, yangi partiyani kiritish soatlab vaqt oladi. Kerak bo‘lgani — tez kassa, aniq ombor va hisobotlar, va bir nechta dorixonaga xizmat qiladigan bitta tizim.",
        "my_role": "Backend va frontendni to‘liq qildim: multi-tenant ma’lumotlar modeli, kassa, ombor, importlar, hisobotlar va super-admin konsoli.",
        "features": [
            ("Kassa", [
                "USB shtrix-kod skaneri: tugmalar orasidagi vaqtga qarab skanerni odam yozishidan ajratish",
                "Qadoq yoki dona bo‘yicha sotish, foiz yoki summa chegirma",
                "Savat brauzerda saqlanadi — sahifa yangilansa sotuv yo‘qolmaydi",
            ]),
            ("Ombor", [
                "Qoldiq donalarda hisoblanadi, partiyalar va yaroqlilik muddati bilan",
                "Muddati yaqin va kam qolgan tovarlar ogohlantirishi",
                "Yetkazib beruvchi nakladnoylari va boshlang‘ich katalogni Excel’dan import",
            ]),
            ("Boshqaruv", [
                "Smenalar, xarajatlar, mijozlar, yetkazib beruvchilar",
                "Sotuvlar tahlili: kunlik dinamika, eng ko‘p sotilganlar",
                "Super-admin: dorixonalar, obunalar, bloklash",
                "Uch til: o‘zbek, rus, tojik",
            ]),
        ],
        "arch": [
            ("Mijoz", ["React 19 + Vite", "TanStack Query", "Kassa savati (localStorage)"]),
            ("API", ["NestJS", "Rollar: super-admin / admin / kassir", "Multi-tenant"]),
            ("Ma’lumot", ["PostgreSQL (Prisma)", "Partiyalar va sotuvlar"]),
        ],
        "decisions": [
            ("Hisob-kitob ikki tomonda bir xil", "Chegirma va jami summa formulasi mijozda ham, serverda ham aynan bir xil. Kassir ekranda ko‘rgan summa server hisoblagan summaga har doim teng."),
            ("Qoldiq — donada", "Tovar qadoqda ham, donada ham sotiladi. Qoldiq faqat donada saqlanadi, qadoq esa hisoblanadi — shunda “yarim qadoq” xatolari bo‘lmaydi."),
            ("Og‘ir kutubxona — faqat kerak joyda", "Excel o‘qish kutubxonasi katta, shuning uchun import sahifalari alohida yuklanadi (lazy). Kassa sahifasi tez ochiladi."),
        ],
    },
    {
        "slug": "almazpro",
        "tag": "E-commerce",
        "title": "Almazpro — o‘yin valyutasi do‘koni",
        "name": "Almazpro",
        "site": ("https://almazpro.uz", "almazpro.uz"),
        "role": "Full-stack · backend va veb-sayt",
        "summary": "Bigo Live foydalanuvchilari uchun almaz sotuvchi do‘kon. To‘lovdan so‘ng almazlar foydalanuvchi ID’siga <b>avtomatik</b>, provayder API orqali yetkaziladi.",
        "points": [
            "Buyurtma → to‘lov → yetkazish zanjiri navbat orqali",
            "To‘lov provayderi integratsiyasi va webhook’lar",
            "Admin panel ikki bosqichli autentifikatsiya (TOTP) bilan",
            "4 tilli sayt: ru, uz, en, tg",
        ],
        "stack": ["NestJS", "Prisma", "PostgreSQL", "BullMQ", "Next.js", "next-intl"],
        "featured": False,
        "problem": "Almaz sotuvchilar odatda buyurtmani qo‘lda bajaradi: to‘lovni tekshiradi, keyin almazni qo‘lda jo‘natadi. Bu sekin, xatoli va tunda ishlamaydi. Maqsad — odam aralashmasdan, to‘lovdan keyin soniyalarda yetkazib beradigan do‘kon.",
        "my_role": "Backend va veb-saytni qildim: buyurtmalar, to‘lov integratsiyasi, avtomatik yetkazish, narxlar va paketlar, admin panel.",
        "features": [
            ("Mijoz uchun", [
                "Paket tanlash, Bigo ID kiritish, to‘lov va buyurtma holatini kuzatish",
                "To‘rt tilli interfeys",
            ]),
            ("Avtomatik yetkazish", [
                "To‘lov tasdiqlangach buyurtma navbatga tushadi va provayder API orqali yetkaziladi",
                "Xato bo‘lsa — navbatda qayta urinish, holat adminga ko‘rinadi",
                "Limitlar va narxlash qoidalari",
            ]),
            ("Admin", [
                "Buyurtmalar ro‘yxati va filtrlar, paketlar va narxlar",
                "Ikki bosqichli kirish (TOTP), bildirishnomalar",
            ]),
        ],
        "arch": [
            ("Mijoz", ["Next.js sayt", "next-intl (4 til)"]),
            ("API", ["Buyurtmalar", "To‘lovlar va webhook", "Admin + TOTP"]),
            ("Fon ishlari", ["BullMQ: yetkazish", "Bildirishnomalar"]),
            ("Tashqi", ["To‘lov provayderi", "Bigo Open Platform"]),
        ],
        "decisions": [
            ("To‘lov va yetkazish — alohida qadamlar", "Webhook faqat to‘lovni qayd qiladi va yetkazish vazifasini navbatga qo‘yadi. Provayder API sekin yoki ishlamay qolsa, to‘lov yo‘qolmaydi — yetkazish keyinroq qayta urinib ko‘riladi."),
            ("Admin uchun ikkinchi omil", "Admin panel pulga bevosita ta’sir qiladi, shuning uchun parol yetarli emas — TOTP (ikki bosqichli autentifikatsiya) majburiy."),
        ],
    },
    {
        "slug": "klinika-erp",
        "tag": "ERP · SMS",
        "title": "Klinika ERP — qabul va SMS eslatmalar",
        "name": "Klinika ERP",
        "site": ("https://www.proktologmirzohid.uz/", "Mijoz: proktologmirzohid.uz"),
        "visit_label": "Shifokor saytini ochish",
        "role": "Full-stack · ichki ERP (shifokor sayti boshqa jamoa ishi)",
        "summary": "Shifokor uchun ichki tizim: bemorlarning qabul vaqtlari saqlanadi va har bir bemorga kelishidan oldin <b>SMS eslatma</b> yuboriladi. Qancha vaqt oldin eslatilishini shifokorning o‘zi tanlaydi.",
        "points": [
            "Bemorlar va qabul vaqtlari jadvali",
            "Qabuldan oldin avtomatik SMS eslatma",
            "Eslatish muddati dinamik — shifokor o‘zi sozlaydi",
            "Eslatmalar Redis va BullMQ navbati orqali rejalashtiriladi",
        ],
        "stack": ["NestJS", "React", "Redis", "BullMQ", "SMS xizmati"],
        "featured": False,
        "problem": "Bemor qabul vaqtini unutib qo‘ysa, shifokorning vaqti bo‘sh ketadi, navbatdagi boshqa bemor esa o‘sha vaqtni ololmaydi. Qo‘ng‘iroq qilib eslatish har kuni qo‘lda qilinadigan ish. Tizim buni avtomatlashtiradi: qabul yozilgan zahoti eslatma rejalashtiriladi.",
        "my_role": "Shifokorning ichki ERP tizimini qildim: NestJS backend, React interfeys, SMS eslatmalar. Ommaviy sayt (proktologmirzohid.uz) boshqa jamoa tomonidan qilingan — u bu yerda faqat mijozni ko‘rsatish uchun.",
        "features": [
            ("Qabul", [
                "Bemorni va qabul vaqtini kiritish",
                "Qabullar jadvali",
            ]),
            ("SMS eslatmalar", [
                "Har bir qabul uchun kelishdan oldin avtomatik SMS",
                "Eslatish muddatini shifokor o‘zi tanlaydi (masalan, bir kun yoki bir necha soat oldin)",
                "Eslatmalar navbatda rejalashtiriladi va vaqti kelganda yuboriladi",
            ]),
        ],
        "arch": [
            ("Interfeys", ["React (shifokor paneli)"]),
            ("API", ["NestJS", "Qabullar", "Sozlamalar"]),
            ("Fon ishlari", ["BullMQ navbati", "Redis"]),
            ("Tashqi", ["SMS xizmati"]),
        ],
        "decisions": [
            ("Eslatma — navbatdagi rejalashtirilgan vazifa", "Eslatma vaqti = qabul vaqti − shifokor tanlagan muddat. Qabul saqlanganda shu vaqtga vazifa BullMQ navbatiga qo‘yiladi; Redis uni saqlaydi va vaqti kelganda ishchi SMS yuboradi. Server qayta ishga tushsa ham rejalashtirilgan eslatmalar yo‘qolmaydi."),
            ("Muddat — sozlama, kodda emas", "Qancha oldin eslatish kerakligi shifokorning sozlamasida turadi. Uni o‘zgartirish uchun dasturchi kerak emas — shifokor o‘zi tanlaydi."),
        ],
    },
    {
        "slug": "autotrad",
        "tag": "Bot",
        "title": "AutoTrad — bozor signallari boti",
        "name": "AutoTrad bot",
        "site": None,
        "site_label": "AutoTrad bot",
        "role": "To‘liq o‘zim",
        "summary": "Binance Futures juftliklarini real vaqtda kuzatib, “M” va “W” grafik naqshlarini topadigan va Telegram’ga signal yuboradigan bot.",
        "points": [
            "WebSocket orqali real-vaqt shamlar, halqali bufer (ring buffer) keshi",
            "Swing nuqtalarni aniqlash va naqsh ishonchliligini baholash",
            "SQLite’da dublikat signallarni filtrlash, cron rejalashtiruvchi",
        ],
        "stack": ["TypeScript", "Node.js", "grammY", "SQLite", "Zod", "Vitest", "Docker"],
        "featured": False,
        "problem": "Yuzlab juftlikni bir necha taymfreymda qo‘lda kuzatish imkonsiz. Bot eng faol juftliklarni o‘zi tanlaydi, grafikni real vaqtda o‘qiydi va faqat sifatli naqsh paydo bo‘lganda xabar beradi.",
        "my_role": "Botni noldan yozdim: birja integratsiyasi, naqshlarni aniqlash algoritmi, signal formatlash va Telegram, saqlash va deploy.",
        "features": [
            ("Ma’lumot", [
                "Hajm bo‘yicha eng faol juftliklar REST orqali tanlanadi va davriy yangilanadi",
                "Shamlar WebSocket orqali real vaqtda keladi va halqali buferda saqlanadi — xotira cheklangan",
            ]),
            ("Tahlil", [
                "Swing high / low nuqtalarini aniqlash",
                "Double Top (M) va Double Bottom (W) naqshlari, har biri ishonchlilik bali bilan",
            ]),
            ("Signal", [
                "Bir xil signal qayta yuborilmasligi uchun SQLite’da dedup",
                "grammY orqali formatlangan Telegram xabari",
                "Zod bilan konfiguratsiya tekshiruvi, to‘g‘ri to‘xtash (graceful shutdown), Vitest testlari",
            ]),
        ],
        "arch": [
            ("Manba", ["Binance REST", "Binance WebSocket"]),
            ("Yadro", ["Candle store (ring buffer)", "Swing detector", "M / W detectorlar"]),
            ("Chiqish", ["SQLite dedup", "Telegram (grammY)", "Cron rejalashtiruvchi"]),
        ],
        "decisions": [
            ("Halqali bufer", "Har juftlik uchun faqat oxirgi N sham kerak. Halqali bufer xotirani qat’iy cheklaydi — bot haftalab ishlaganda ham o‘smaydi."),
            ("Signal — bir marta", "Bir naqsh bir necha sham davomida ko‘rinib turadi. SQLite’dagi dedup yozuvlari foydalanuvchiga bir xil signalni takror yubormaslikni kafolatlaydi."),
        ],
    },
    {
        "slug": "talim",
        "tag": "Ta’lim",
        "title": "Ta’lim loyihalari",
        "name": "Ta’lim loyihalari",
        "site": None,
        "site_label": "JLPT Master · Yuksalish avtotest",
        "role": "Full-stack",
        "summary": "Yapon tilini o‘rganish platformasi va o‘quv markazlari uchun haydovchilik imtihoni dasturi.",
        "points": [
            "JLPT Master: darslar, video, testlar, AI izohlar, Payme, QR kodli sertifikat",
            "Yuksalish avtotest: internetsiz ishlaydigan kiosk, 1 197 savol uch tilda, server bilan sinxronlash",
        ],
        "stack": ["NestJS", "Prisma", "BullMQ", "Socket.IO", "Electron", "React", "PostgreSQL"],
        "featured": False,
        "problem": "Ikki xil ta’lim muammosi. Birinchisi — o‘zbek tilida yapon tilini (JLPT N5 / N4) tizimli o‘rganish imkoniyati kam. Ikkinchisi — haydovchilik maktablarida test dasturi internetsiz ishlashi kerak, savollar esa markazlashgan holda yangilanishi kerak.",
        "my_role": "Ikkala loyihada ham backend va mijoz qismini qildim.",
        "features": [
            ("JLPT Master", [
                "Ketma-ket ochiladigan darslar: oldingi dars o‘tilmaguncha keyingisi yopiq",
                "Video darslar, testlar va natijalar",
                "AI orqali javoblarga izoh (bir nechta AI provayderi sozlanadi)",
                "Payme orqali to‘lov va obuna, QR kodli PDF sertifikat",
                "Push bildirishnomalar va real-vaqt (Socket.IO)",
            ]),
            ("Yuksalish avtotest", [
                "Electron ilova, kiosk rejimi: o‘quvchi chiqib keta olmaydi",
                "Internetsiz ishlaydi; savollar va rasmlar lokal nusxada",
                "1 197 savol uch tilda (o‘zbek lotin, kirill, rus), mavzular bo‘yicha",
                "Server bilan sinxronlash: faqat o‘zgargan mavzular tortiladi, natijalar navbatda kutib, tarmoq paydo bo‘lganda yuboriladi",
            ]),
        ],
        "arch": [
            ("JLPT Master", ["NestJS 11 + Prisma", "BullMQ + Redis", "S3 video", "Socket.IO"]),
            ("Avtotest", ["Electron + React", "Lokal ma’lumot qatlami", "NestJS sinxronlash serveri"]),
        ],
        "decisions": [
            ("Oflayn-birinchi avtotest", "Ilova ikki qatlamli ma’lumot bilan ishlaydi: o‘rnatilgan (faqat o‘qish) va yoziladigan qatlam. Natijalar “chiquvchi navbat”ga yoziladi va tarmoq bo‘lganda yuboriladi — internet uzilsa hech narsa yo‘qolmaydi."),
            ("Faqat o‘zgargan narsani yuklash", "Server manifestini lokal holat bilan solishtirib, faqat o‘zgargan mavzular yuklanadi — sekin internetli markazlar uchun muhim."),
        ],
    },
]

POSTS = [
    {
        "slug": "system-design-15-case-studies",
        "title": "15 ta mashhur tizim noldan: System Design darsligi",
        "excerpt": "ChatGPT, YouTube, Spotify, Google Docs va boshqa tizimlar qanday ishlaydi — eng sodda yechimdan bugungi arxitekturagacha, hisob-kitob va amaliy topshiriqlar bilan.",
        "url": "https://dinmuhammad05.github.io/15-case-studiesfo-software-engineers/",
        "cta": "Darslikni ochish",
        "stats": [("10", "tayyor dars"), ("10–20 ming", "so‘z har darsda"), ("15–35", "hisob-kitob har darsda")],
        "body": [
            "Tizim dizaynini o‘rganishdagi eng katta muammo — mavzular havoda qoladi: “kesh qo‘ying”, “navbat qo‘shing”. Nega aynan shu yerda, qancha foyda beradi, va evaziga nima yo‘qotiladi — bu savollar ko‘pincha javobsiz qoladi.",
            "Bu darslikda har bir dars bitta haqiqiy tizim atrofida qurilgan va bir xil yo‘ldan boradi: muammo va raqamlar, eng sodda ishlaydigan yechim, u qayerda sinadi, va o‘n to‘rt qadamlik evolyutsiya — har bir qadamda nima yutilgani va nima yo‘qotilgani bilan. Keyin ishonchlilik, xavfsizlik, iqtisod, intervyu savollari va amaliy topshiriq.",
            "Har bir darsning dizayni o‘sha mahsulotga o‘xshaydi: Spotify darsi pleylist kabi, Google Docs darsi hujjat kabi, YouTube darsi video sahifasi kabi. Hozir tayyor: ChatGPT, URL qisqartiruvchi, Redis, Twitter tasmasi, Reddit, Slack, WhatsApp, YouTube, Spotify va Google Docs.",
            "Amaliy qismda har bir dars uchun tayyor kod bor: simulyator yoki o‘lchov skripti va o‘quvchi to‘ldiradigan qism. Tekshiruvlar esa “ishladi” emas, raqam bilan: masalan, Google Docs darsida o‘zingiz yozgan operatsion transformatsiya 20 000 ta tasodifiy juftlik va yuzlab simulyatsiya bilan sinaladi.",
        ],
    },
    {
        "slug": "kodla",
        "title": "Kodla: JavaScript’dan DevOps’gacha, o‘zbek tilida",
        "excerpt": "226 ta dars va 559 ta interaktiv kod maydonchasi — dasturlashni noldan, chuqur va o‘zbek tilida o‘rganish uchun.",
        "url": "https://dinmuhammad05.github.io/javascript-info/",
        "cta": "Kodla saytini ochish",
        "stats": [("226", "dars"), ("559", "interaktiv misol"), ("7", "qism")],
        "body": [
            "Kodla — web dasturlashni o‘zbek tilida noldan o‘rgatuvchi interaktiv sayt. JavaScript qismi javascript.info o‘quv dasturi tuzilishidan ilhomlangan, keyin esa backend, frontend va DevOps mavzulari bilan davom etadi.",
            "Saytning asosiy xususiyati — misollarni o‘qib qolmasdan, shu yerning o‘zida o‘zgartirib ishga tushirish mumkin: 559 ta kod maydonchasi natijani darhol ko‘rsatadi.",
            "Texnik tomondan sayt tashqi kutubxonasiz, sof HTML, CSS va JavaScript. Darslar alohida blok formatidagi fayllarda saqlanadi, kichik Node.js generator esa ulardan bir xil dizaynli sahifalar yasaydi — yangi mavzu qo‘shish bitta fayl yozishdan iborat.",
        ],
    },
    {
        "slug": "tizim-dizayni-kursi",
        "title": "Tizim dizayni kursi: 15 mavzu, ikki qatlam",
        "excerpt": "Mikroservislar, modulli monolit, keshlash, sharding, replikatsiya va boshqalar — har mavzu “Core” va chuqur “Deep/Senior” qatlami bilan, NestJS misollari bilan.",
        "url": "https://dinmuhammad05.github.io/system-design/",
        "cta": "Kursni ochish",
        "stats": [("15", "mavzu"), ("30", "dars"), ("NestJS", "misollar")],
        "body": [
            "Bu kurs arxitektura naqshlariga bag‘ishlangan. Har bir mavzu ikki qatlamda yozilgan: Core — mavzuni noldan tushunish (nega kerak, asosiy g‘oya, NestJS’da qanday qilinadi), va Deep — ichki mexanika, nozik holatlar va senior darajadagi tekshiruv ro‘yxati.",
            "Mavzular: mikroservislar, modulli monolit, hodisalarga asoslangan arxitektura, keshlash, yuklamani taqsimlash, sharding, replikatsiya, API gateway va boshqalar.",
            "Case-study darsligidan farqi: u yerda bitta tizim ichidagi qarorlar ko‘riladi, bu yerda esa naqshlarning o‘zi — ularni keyin istalgan loyihada qo‘llash uchun.",
        ],
    },
    {
        "slug": "tizim-dizayni-chuqur-kurs",
        "title": "Tizim dizayni: kompyuterning o‘zidan boshlab",
        "excerpt": "Katta tizimlarni eng pastki qatlamdan o‘rganish: kompyuter anatomiyasi, operatsion tizim, protsess va thread, virtual xotira.",
        "url": "https://dinmuhammad05.github.io/sys_design_44/kurs/",
        "cta": "Kursni ochish",
        "stats": [("7", "dars hozircha"), ("PWA", "oflayn o‘qish")],
        "body": [
            "Ko‘p tizim dizayni kurslari to‘g‘ridan-to‘g‘ri serverlar va ma’lumotlar bazalaridan boshlaydi. Bu kurs bir qadam pastdan boshlaydi: kompyuterning o‘zi qanday ishlaydi, resurslar qayerda tugaydi, operatsion tizim nimani yashiradi.",
            "Hozircha ikki bo‘lim tayyor: kompyuter anatomiyasi (tizim yuragi, resurslar chegarasi, real rollar) va operatsion tizim (asosiy tushunchalar, protsess va thread, virtual xotira va izolyatsiya, tizim chaqiruvlari).",
            "Sayt sof HTML/CSS/JS, build jarayonisiz; o‘rnatib, internetsiz o‘qish mumkin (PWA).",
        ],
    },
]
